version: '3.6'

services:
  app:
    build:
      context: .
    command: ["--bind", "0.0.0.0:8000", "wsgi"]
    entrypoint: ["gunicorn"]
    ports:
      - 8000
    networks:
      - network-teste
  web:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - network-teste

networks:
  network-teste:
    driver: bridge